# production environment
FROM nginx:stable-alpine
COPY front-end/build /usr/share/nginx/html
COPY front-end/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
